#include "Limelight-internal.h"
#include "SecondStream.h"

#include <stdatomic.h>

STREAM_CONFIGURATION SecondStreamConfig;
DECODER_RENDERER_CALLBACKS VideoCallbacks2;
SS_PING VideoPingPayload2;
uint16_t VideoPortNumber2;
bool SecondStreamEnabled;

static atomic_bool secondStreamFailed;
static atomic_bool secondStreamInitialized;
static atomic_bool secondStreamStarted;
static atomic_bool secondStreamStatusActive;
static atomic_bool secondStreamLifecycleMutexInitialized;
static atomic_uint secondStreamGeneration;
static atomic_int secondStreamFailureCode;
static _Atomic(SECOND_DISPLAY_STATUS_CALLBACK) secondStreamStatusCallback;
static PLT_MUTEX secondStreamLifecycleMutex;

/** Failure notification captured for delivery away from the receive thread. */
typedef struct _SECOND_DISPLAY_FAILURE_NOTIFICATION {
    SECOND_DISPLAY_STATUS_CALLBACK callback;  ///< Callback belonging to the failed session.
    unsigned int generation;  ///< Session generation used to reject stale reconnect callbacks.
    int errorCode;  ///< Native receive-stream failure.
} SECOND_DISPLAY_FAILURE_NOTIFICATION, *PSECOND_DISPLAY_FAILURE_NOTIFICATION;

/**
 * @brief Publish a second-display status transition exactly once.
 *
 * @param active Whether stream two is currently usable.
 * @param errorCode Failure code, or zero for an intentional transition.
 */
static void notifySecondDisplayStatus(bool active, int errorCode) {
    SECOND_DISPLAY_STATUS_CALLBACK callback = atomic_load(&secondStreamStatusCallback);
    bool previous = atomic_exchange(&secondStreamStatusActive, active);
    if (previous != active && callback != NULL) {
        callback(active, errorCode);
    }
}

/**
 * @brief Deliver an asynchronous second-stream failure notification.
 *
 * @param context Captured `SECOND_DISPLAY_FAILURE_NOTIFICATION` instance.
 */
static void secondDisplayFailureNotificationThread(void* context) {
    PSECOND_DISPLAY_FAILURE_NOTIFICATION notification = context;

    if (notification->generation == atomic_load(&secondStreamGeneration)) {
        notification->callback(false, notification->errorCode);
    }

    free(notification);
}

/**
 * @brief Publish failure without running client teardown on the receive thread.
 *
 * A client is allowed to detach the second display from this callback. Dispatch
 * on another thread prevents that detach from trying to join the receive thread
 * that is currently executing the callback.
 *
 * @param errorCode Native receive-stream failure.
 */
static void notifySecondDisplayFailure(int errorCode) {
    PSECOND_DISPLAY_FAILURE_NOTIFICATION notification;
    SECOND_DISPLAY_STATUS_CALLBACK callback;
    PLT_THREAD notificationThread;
    int err;

    callback = atomic_load(&secondStreamStatusCallback);
    if (!atomic_exchange(&secondStreamStatusActive, false) || callback == NULL) {
        return;
    }

    notification = malloc(sizeof(*notification));
    if (notification == NULL) {
        Limelog("Unable to allocate second display failure callback\n");
        return;
    }

    notification->callback = callback;
    notification->generation = atomic_load(&secondStreamGeneration);
    notification->errorCode = errorCode;

    err = PltCreateThread("SecondDispFail", secondDisplayFailureNotificationThread,
                          notification, &notificationThread);
    if (err != 0) {
        Limelog("Unable to start second display failure callback thread: %d\n", err);
        free(notification);
        return;
    }

    PltDetachThread(&notificationThread);
}

void LiRequestIdrFrameForStream2(void) {
    LiRequestIdrFrameForStream(1);
}

void connectionDetectedFrameLoss2(uint32_t startFrame, uint32_t endFrame) {
    connectionDetectedFrameLossForStream(1, startFrame, endFrame);
}

/**
 * @brief Ignore second-stream completion statistics.
 *
 * @param frameIndex Completed frame number from stream two.
 */
void connectionReceivedCompleteFrame2(uint32_t frameIndex) {
    (void) frameIndex;
}

/**
 * @brief Ignore second-stream loss-statistics frame observations.
 *
 * @param frameIndex Observed frame number from stream two.
 */
void connectionSawFrame2(uint32_t frameIndex) {
    (void) frameIndex;
}

/**
 * @brief Ignore stream-two FEC telemetry that lacks a stream identifier.
 *
 * @param fecStatus FEC status generated by the second RTP queue.
 */
void connectionSendFrameFecStatus2(PSS_FRAME_FEC_STATUS fecStatus) {
    (void) fecStatus;
}

bool isReferenceFrameInvalidationEnabledForStream2(void) {
    return ReferenceFrameInvalidationSupported &&
           (((NegotiatedVideoFormat & VIDEO_FORMAT_MASK_H264) &&
             (VideoCallbacks2.capabilities & CAPABILITY_REFERENCE_FRAME_INVALIDATION_AVC)) ||
            ((NegotiatedVideoFormat & VIDEO_FORMAT_MASK_H265) &&
             (VideoCallbacks2.capabilities & CAPABILITY_REFERENCE_FRAME_INVALIDATION_HEVC)) ||
            ((NegotiatedVideoFormat & VIDEO_FORMAT_MASK_AV1) &&
             (VideoCallbacks2.capabilities & CAPABILITY_REFERENCE_FRAME_INVALIDATION_AV1)));
}

static void secondStreamStageStarting(int stage) {
    (void) stage;
}

static void secondStreamStageComplete(int stage) {
    (void) stage;
}

static void secondStreamStageFailed(int stage, int errorCode) {
    (void) stage;
    (void) errorCode;
}

static void secondStreamConnectionStarted(void) {
}

static void secondStreamConnectionTerminated(int errorCode) {
    atomic_store(&secondStreamFailureCode, errorCode);
    if (atomic_exchange(&secondStreamFailed, true)) {
        return;
    }

    Limelog("Second display stream ended: %d. Continuing with one display.\n", errorCode);
    notifySecondDisplayFailure(errorCode);
}

static void secondStreamLogMessage(const char* format, ...) {
    (void) format;
}

static void secondStreamRumble(unsigned short controllerNumber, unsigned short lowFreqMotor, unsigned short highFreqMotor) {
    (void) controllerNumber;
    (void) lowFreqMotor;
    (void) highFreqMotor;
}

static void secondStreamConnectionStatusUpdate(int connectionStatus) {
    (void) connectionStatus;
}

static void secondStreamSetHdrMode(bool enabled) {
    (void) enabled;
}

static void secondStreamRumbleTriggers(uint16_t controllerNumber, uint16_t leftTriggerMotor, uint16_t rightTriggerMotor) {
    (void) controllerNumber;
    (void) leftTriggerMotor;
    (void) rightTriggerMotor;
}

static void secondStreamSetMotionEventState(uint16_t controllerNumber, uint8_t motionType, uint16_t reportRateHz) {
    (void) controllerNumber;
    (void) motionType;
    (void) reportRateHz;
}

static void secondStreamSetControllerLED(uint16_t controllerNumber, uint8_t r, uint8_t g, uint8_t b) {
    (void) controllerNumber;
    (void) r;
    (void) g;
    (void) b;
}

CONNECTION_LISTENER_CALLBACKS SecondStreamListenerCallbacks = {
    .stageStarting = secondStreamStageStarting,
    .stageComplete = secondStreamStageComplete,
    .stageFailed = secondStreamStageFailed,
    .connectionStarted = secondStreamConnectionStarted,
    .connectionTerminated = secondStreamConnectionTerminated,
    .logMessage = secondStreamLogMessage,
    .rumble = secondStreamRumble,
    .connectionStatusUpdate = secondStreamConnectionStatusUpdate,
    .setHdrMode = secondStreamSetHdrMode,
    .rumbleTriggers = secondStreamRumbleTriggers,
    .setMotionEventState = secondStreamSetMotionEventState,
    .setControllerLED = secondStreamSetControllerLED,
};

void LiInitializeSecondDisplay(int width, int height, int fps, int bitrateKbps,
                               PDECODER_RENDERER_CALLBACKS drCallbacks,
                               SECOND_DISPLAY_STATUS_CALLBACK statusCallback) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    memset(&SecondStreamConfig, 0, sizeof(SecondStreamConfig));
    memset(&VideoCallbacks2, 0, sizeof(VideoCallbacks2));
    memset(&VideoPingPayload2, 0, sizeof(VideoPingPayload2));

    SecondStreamConfig.width = width;
    SecondStreamConfig.height = height;
    SecondStreamConfig.fps = fps;
    SecondStreamConfig.bitrate = bitrateKbps;

    if (drCallbacks != NULL) {
        VideoCallbacks2 = *drCallbacks;
    }

    atomic_store(&secondStreamStatusCallback, statusCallback);
    atomic_fetch_add(&secondStreamGeneration, 1);
    atomic_store(&secondStreamFailed, false);
    atomic_store(&secondStreamInitialized, false);
    atomic_store(&secondStreamStarted, false);
    atomic_store(&secondStreamStatusActive, false);
    atomic_store(&secondStreamFailureCode, 0);
    VideoPortNumber2 = 0;

    SecondStreamEnabled = drCallbacks != NULL && width > 0 && height > 0 &&
                          fps > 0 && bitrateKbps > 0;

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }
}

void LiPrepareSecondDisplay(void) {
    if (!SecondStreamEnabled) {
        return;
    }

    if (!atomic_load(&secondStreamLifecycleMutexInitialized)) {
        int mutexErr = PltCreateMutex(&secondStreamLifecycleMutex);
        if (mutexErr != 0) {
            Limelog("Unable to create second display lifecycle mutex: %d\n", mutexErr);
            LiDisableSecondDisplay();
            return;
        }
        atomic_store(&secondStreamLifecycleMutexInitialized, true);
    }

    PltLockMutex(&secondStreamLifecycleMutex);

    int width = SecondStreamConfig.width;
    int height = SecondStreamConfig.height;
    int fps = SecondStreamConfig.fps;
    int bitrate = SecondStreamConfig.bitrate;

    // Copy only after LiStartConnection() has installed this session's keys,
    // codec flags, packet size, colour mode, and remote/local policy.
    SecondStreamConfig = StreamConfig;
    SecondStreamConfig.width = width;
    SecondStreamConfig.height = height & ~0x1;
    SecondStreamConfig.fps = fps;
    SecondStreamConfig.bitrate = bitrate;

    if (height != SecondStreamConfig.height) {
        Limelog("Second display encoder height must not be odd. Rounding %d to %d\n",
                height, SecondStreamConfig.height);
    }

    if (SecondStreamConfig.height == 0) {
        Limelog("Second display encoder height is invalid after alignment\n");
        SecondStreamEnabled = false;
    }

    PltUnlockMutex(&secondStreamLifecycleMutex);
}

void LiSetSecondDisplayPacketSize(int packetSize) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    if (SecondStreamEnabled) {
        SecondStreamConfig.packetSize = packetSize;
    }

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }
}

int LiStartSecondDisplayStream(void* rendererContext, int drFlags) {
    int err;

    if (!LiIsSecondDisplayNegotiated()) {
        return 0;
    }

    if (!atomic_load(&secondStreamLifecycleMutexInitialized)) {
        return -1;
    }

    PltLockMutex(&secondStreamLifecycleMutex);

    // A Surface detach may race with the RTSP-to-start transition.
    if (!SecondStreamEnabled || VideoPortNumber2 == 0) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
        return 0;
    }

    atomic_store(&secondStreamFailed, false);
    initializeVideoStream2();
    atomic_store(&secondStreamInitialized, true);

    err = startVideoStream2(rendererContext, drFlags);
    if (err != 0) {
        destroyVideoStream2();
        atomic_store(&secondStreamInitialized, false);
        SecondStreamEnabled = false;
        VideoPortNumber2 = 0;
        PltUnlockMutex(&secondStreamLifecycleMutex);
        return err;
    }

    // A receive failure can occur immediately after its thread is created. Do
    // not announce an active display after that failure has already happened.
    if (atomic_load(&secondStreamFailed)) {
        stopVideoStream2();
        destroyVideoStream2();
        atomic_store(&secondStreamInitialized, false);
        SecondStreamEnabled = false;
        VideoPortNumber2 = 0;
        PltUnlockMutex(&secondStreamLifecycleMutex);
        return -1;
    }

    atomic_store(&secondStreamStarted, true);
    PltUnlockMutex(&secondStreamLifecycleMutex);

    // A Surface can be detached immediately after the start lock is released.
    // Do not resurrect the UI's active state after that teardown completed.
    if (atomic_load(&secondStreamStarted)) {
        notifySecondDisplayStatus(true, 0);

        /*
         * The receive thread can fail after the pre-start failure check but
         * before the active transition above. Its first notification observes
         * an already-inactive status and intentionally emits nothing. Recheck
         * after publishing so that race is closed with an ordered inactive
         * callback carrying the original failure code.
         */
        if (atomic_load(&secondStreamFailed)) {
            notifySecondDisplayFailure(atomic_load(&secondStreamFailureCode));
        }
    }
    return 0;
}

void LiStopSecondDisplayStream(void) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    if (atomic_exchange(&secondStreamStarted, false)) {
        stopVideoStream2();
    }

    if (atomic_exchange(&secondStreamInitialized, false)) {
        destroyVideoStream2();
    }

    SecondStreamEnabled = false;
    VideoPortNumber2 = 0;

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }

    // This is idempotent. An asynchronous failure transitions the status first,
    // so subsequent Surface teardown cannot issue a duplicate callback.
    notifySecondDisplayStatus(false, 0);
}

void LiHandleSecondDisplayTermination(int errorCode) {
    // Report the host's reason before teardown. This transitions the status
    // atomically, so LiStopSecondDisplayStream() cannot emit a second inactive
    // notification with an unhelpful zero error code.
    secondStreamConnectionTerminated(errorCode);
    LiStopSecondDisplayStream();
}

void LiDestroySecondDisplayState(void) {
    LiStopSecondDisplayStream();

    atomic_fetch_add(&secondStreamGeneration, 1);
    atomic_store(&secondStreamStatusCallback, NULL);

    if (atomic_exchange(&secondStreamLifecycleMutexInitialized, false)) {
        PltDeleteMutex(&secondStreamLifecycleMutex);
    }
}

void LiDisableSecondDisplay(void) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    SecondStreamEnabled = false;
    VideoPortNumber2 = 0;

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }
}

bool LiIsSecondDisplayNegotiated(void) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);
    bool negotiated;

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    negotiated = SecondStreamEnabled && !atomic_load(&secondStreamFailed) &&
                 VideoPortNumber2 != 0;

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }

    return negotiated;
}

bool LiIsSecondDisplayRequested(void) {
    bool mutexInitialized = atomic_load(&secondStreamLifecycleMutexInitialized);
    bool requested;

    if (mutexInitialized) {
        PltLockMutex(&secondStreamLifecycleMutex);
    }

    requested = SecondStreamEnabled;

    if (mutexInitialized) {
        PltUnlockMutex(&secondStreamLifecycleMutex);
    }

    return requested;
}

bool LiIsSecondDisplayActive(void) {
    return LiIsSecondDisplayNegotiated() && atomic_load(&secondStreamStarted);
}
