#pragma once

#include "Limelight.h"
#include "Video.h"

/**
 * @file SecondStream.h
 * @brief Internal API for Moonlight's optional second video stream.
 *
 * The wire format is documented in Sunshine DS's
 * `docs/dual_display_protocol.md`. The receive, RTP/FEC, depacketizer, and
 * decoder layers all retain file-static state upstream, so each of those source
 * files is compiled a second time with renamed public symbols. This leaves the
 * established stream-zero path unchanged while ensuring that no packet queue,
 * frame chain, decoder queue, or callback is shared between displays.
 */

/** Callback used to publish second-display availability changes to the client. */
typedef void (*SECOND_DISPLAY_STATUS_CALLBACK)(bool active, int errorCode);

/**
 * @brief Initialize the second video stream's receive pipeline.
 */
void initializeVideoStream2(void);

/**
 * @brief Destroy the second video stream's receive pipeline.
 */
void destroyVideoStream2(void);

/**
 * @brief Start the second video stream's receive pipeline.
 *
 * @param rendererContext Opaque decoder renderer context.
 * @param drFlags Decoder renderer flags.
 * @return Zero on success or a platform error code on failure.
 */
int startVideoStream2(void* rendererContext, int drFlags);

/**
 * @brief Stop the second video stream's receive pipeline.
 */
void stopVideoStream2(void);

/** Full stream configuration used only by the second receive pipeline. */
extern STREAM_CONFIGURATION SecondStreamConfig;

/** Decoder callbacks that render only to the second Android surface. */
extern DECODER_RENDERER_CALLBACKS VideoCallbacks2;

/** Per-socket Sunshine ping payload and sequence counter for stream one. */
extern SS_PING VideoPingPayload2;

/** UDP port negotiated by RTSP for `streamid=video/1/0`, or zero if absent. */
extern uint16_t VideoPortNumber2;

/** Whether the client requested the optional second display for this session. */
extern bool SecondStreamEnabled;

/**
 * @brief Request a decoder refresh after loss on the second video stream.
 *
 * Sunshine DS uses byte zero of the existing two-byte IDR payload as the video
 * stream index. Legacy requests remain all-zero and therefore target stream zero.
 */
void LiRequestIdrFrameForStream2(void);

/**
 * @brief Queue a reference-frame invalidation range from stream two.
 *
 * @param startFrame First lost frame number in the second stream.
 * @param endFrame Last lost frame number in the second stream.
 */
void connectionDetectedFrameLoss2(uint32_t startFrame, uint32_t endFrame);

/**
 * @brief Ignore completion telemetry from stream one.
 *
 * @param frameIndex Completed second-stream frame number.
 */
void connectionReceivedCompleteFrame2(uint32_t frameIndex);

/**
 * @brief Ignore loss-statistics observations from stream one.
 *
 * @param frameIndex Observed second-stream frame number.
 */
void connectionSawFrame2(uint32_t frameIndex);

/**
 * @brief Ignore FEC telemetry that cannot identify a video stream.
 *
 * @param fecStatus Status generated by the second RTP/FEC queue.
 */
void connectionSendFrameFecStatus2(PSS_FRAME_FEC_STATUS fecStatus);

/**
 * @brief Test whether reference-frame invalidation is safe for stream one.
 *
 * @return True when the server and second decoder both support invalidation.
 */
bool isReferenceFrameInvalidationEnabledForStream2(void);

/** Listener callbacks that isolate optional-stream failures from the session. */
extern CONNECTION_LISTENER_CALLBACKS SecondStreamListenerCallbacks;

/**
 * @brief Arm a second display request before calling LiStartConnection().
 *
 * Session-shared configuration is deliberately copied later, after
 * LiStartConnection() has installed and normalized the current primary stream
 * configuration. This prevents stale packet sizes and encryption keys from a
 * prior session entering the second pipeline.
 *
 * @param width Requested width of the client's second panel.
 * @param height Requested height of the client's second panel.
 * @param fps Requested frame rate of the second stream.
 * @param bitrateKbps Requested bitrate in kilobits per second.
 * @param drCallbacks Decoder callbacks for the second Android surface.
 * @param statusCallback Callback for active/inactive status transitions.
 */
void LiInitializeSecondDisplay(int width, int height, int fps, int bitrateKbps,
                               PDECODER_RENDERER_CALLBACKS drCallbacks,
                               SECOND_DISPLAY_STATUS_CALLBACK statusCallback);

/**
 * @brief Merge the current session configuration into the second request.
 *
 * Called after primary stream validation and packet-size normalization but
 * before SDP generation.
 */
void LiPrepareSecondDisplay(void);

/**
 * @brief Apply the final negotiated video packet payload size to stream one.
 *
 * SDP generation may reduce the primary packet size after second-display
 * configuration was copied, to reserve space for the encrypted-video header.
 * Both RTP/FEC queues must use the same final size advertised to the host.
 *
 * @param packetSize Final video payload size in bytes.
 */
void LiSetSecondDisplayPacketSize(int packetSize);

/**
 * @brief Start the negotiated optional stream and own its lifecycle state.
 *
 * @param rendererContext Opaque decoder renderer context.
 * @param drFlags Decoder renderer flags.
 * @return Zero on success, or an error code after complete local cleanup.
 */
int LiStartSecondDisplayStream(void* rendererContext, int drFlags);

/**
 * @brief Stop and destroy the optional stream if any portion was initialized.
 *
 * Safe to call repeatedly, including after an asynchronous stream failure.
 */
void LiStopSecondDisplayStream(void);

/**
 * @brief Handle a host-reported failure scoped to the second video stream.
 *
 * Publishes the failure to the Android listener and tears down only the
 * optional receive/decode pipeline. The primary video, audio, input, and
 * control streams remain connected.
 *
 * @param errorCode Normalized Moonlight termination error code.
 */
void LiHandleSecondDisplayTermination(int errorCode);

/**
 * @brief Release synchronization state before the platform layer is destroyed.
 *
 * Called once during primary connection teardown after the optional pipeline is
 * stopped. Safe when second-display setup never progressed far enough to create
 * platform synchronization primitives.
 */
void LiDestroySecondDisplayState(void);

/**
 * @brief Give up the current second-display request without affecting stream zero.
 */
void LiDisableSecondDisplay(void);

/**
 * @brief Test whether the client still requests a second display.
 *
 * @return True while the optional request remains armed.
 */
bool LiIsSecondDisplayRequested(void);

/**
 * @brief Test whether RTSP negotiated a distinct second video stream.
 *
 * @return True after a valid, distinct UDP port was negotiated.
 */
bool LiIsSecondDisplayNegotiated(void);

/**
 * @brief Test whether the second stream is started and has not failed.
 *
 * @return True only while the optional stream is usable by the client UI.
 */
bool LiIsSecondDisplayActive(void);
